CREATE TABLE projects (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name text NOT NULL CHECK name (name <> ''),
	priority integer NOT NULL,
	description text,
	deliverydate date NOT NULL
);
-- data

INSERT INTO projects (name, priority , description , deliverydate)
	values ('Make a web app', 1 'Using java', '2021-01-20');

INSERT INTO projects (name, priority , description , deliverydate)
	values ('Make an app', 3 'Using Javascript', '2021-01-20');

INSERT INTO projects (name, priority , description , deliverydate)
	values ('Make a web app', 2 'Using Angular', '2021-01-20');


CREATE TABLE tasks(
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name text NOT NULL CHECK (name <> ''),
	done BOOLEAN, 
	projectID integer REFERENCES projects(id)
);

-- data

INSERT INTO tasks (name, done, projectID) 
    values ('Donwload vuejs', false, 1);

INSERT INTO tasks (name, done, projectID) 
    values ('Make a form', true , 2);

INSERT INTO tasks (name, done, projectID) 
    values ('Make a service', false, 3);
