CREATE TABLE projects (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name text NOT NULL CHECK (name <> ''),
	priority integer NOT NULL,
	description text,
	deliverydate timestamp
);


INSERT INTO projects (name, priority , description)
	values ('Make a web app', 1, 'Using java');

INSERT INTO projects (name, priority , description)
	values ('Make an app', 3 ,'Using Javascript');

INSERT INTO projects (name, priority , description)
	values ('Make a web app', 2, 'Using Angular');

*****************************************************

CREATE TABLE tasks(
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name text NOT NULL CHECK (name <> ''),
	done BOOLEAN, 
	projectID integer REFERENCES projects(id) ON DELETE CASCADE
);

INSERT INTO tasks (name, done, projectID) 
    values ('Donwload vuejs', false, 4);

INSERT INTO tasks (name, done, projectID) 
    values ('Make a form', true , 2);

INSERT INTO tasks (name, done, projectID) 
    values ('Make a service', false, 3);
